version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: asistencia_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-123456}
      - MYSQL_DATABASE=${DB_NAME:-asistencia_db}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-123456}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
volumes:
  db_data:
